workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

stages:
  - format
  - test

Check Black format:
  stage: format
  only:
    - branches
  except:
    - tags
  script:
    - pip install black
    - black . --check --diff --color

Pytest:
  stage: test
  only:
    - branches
  except:
    - tags
  script:
    - apt install python3-pip
    - python -m pip3 install --upgrade pip
    - pip3 install -r requirements.txt
    - apt-get update -y
    - apt-get install -y bedtools
    - python -m pytest --cov=lib --cov-fail-under=90 tests
