workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

stages:
  - format
  - test

Check Black format:
  stage: format
  only:
    - branches
  except:
    - tags
  script:
    - pip install black
    - black . --check --diff --color

Pytest:
  stage: test
  image: python3.11
  only:
    - branches
  except:
    - tags
  before_script:
    - export PYTHONPATH=.:$PYTHONPATH
  script:
    - pip install --upgrade pip 
    - pip install -r requirements.txt
    - apt-get update -y
    - apt-get install -y bedtools
    - pytest --cov=lib --cov-fail-under=90 tests
