# Run python unit test suite

name: Python unit tests

on: [push, pull_request]

jobs:
  test:

    runs-on: oliver-lorenz-sanger/python-cps-extractor:test

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Test with pytest
      run: |
        pytest tests